# Generated by Django 4.2.19 on 2025-02-17 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('disciplina', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('horario', models.TimeField()),
                ('id_professor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.professor')),
            ],
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
    ]
