# Generated by Django 4.2.19 on 2025-02-17 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_professor_turma_delete_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('matricula', models.CharField(max_length=10)),
                ('curso', models.CharField(max_length=100)),
                ('id_turma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.turma')),
            ],
        ),
    ]
